import type { NodeType, Template, StressEvent } from './types'

export const nodeTypes: NodeType[] = [
  {
    type: 'CLIENT',
    label: 'CLIENT',
    icon: '👤',
    desc: 'Traffic source',
    color: '#ff6b4a',
    defaultCapacity: 0,
    defaultLatency: 0,
    costPerInstance: 0,
    defaultReplicas: 1,
    defaultErrorRate: 0,
  },
  {
    type: 'CDN',
    label: 'CDN',
    icon: '🌐',
    desc: 'Edge caching',
    color: '#22d3ee',
    defaultCapacity: 100000,
    defaultLatency: 5,
    costPerInstance: 50,
    defaultReplicas: 1,
    defaultErrorRate: 0.01,
  },
  {
    type: 'RATELIMIT',
    label: 'RATE LIMITER',
    icon: '🚦',
    desc: 'Throttle & protect',
    color: '#f97316',
    defaultCapacity: 50000,
    defaultLatency: 1,
    costPerInstance: 20,
    defaultReplicas: 1,
    defaultErrorRate: 0,
  },
  {
    type: 'LB',
    label: 'LOAD BALANCER',
    icon: '⚖️',
    desc: 'Distributes load',
    color: '#38bdf8',
    defaultCapacity: 50000,
    defaultLatency: 2,
    costPerInstance: 30,
    defaultReplicas: 1,
    defaultErrorRate: 0.01,
  },
  {
    type: 'GATEWAY',
    label: 'API GATEWAY',
    icon: '🛡️',
    desc: 'Route & auth',
    color: '#a78bfa',
    defaultCapacity: 5000,
    defaultLatency: 10,
    costPerInstance: 80,
    defaultReplicas: 1,
    defaultErrorRate: 0.1,
  },
  {
    type: 'SERVICE',
    label: 'MICROSERVICE',
    icon: '⚙️',
    desc: 'Business logic',
    color: '#34d399',
    defaultCapacity: 1000,
    defaultLatency: 50,
    costPerInstance: 100,
    defaultReplicas: 1,
    defaultErrorRate: 0.5,
  },
  {
    type: 'CACHE',
    label: 'CACHE',
    icon: '⚡',
    desc: 'Read-only cache',
    color: '#f472b6',
    defaultCapacity: 20000,
    defaultLatency: 2,
    costPerInstance: 60,
    defaultReplicas: 1,
    defaultErrorRate: 0.01,
  },
  {
    type: 'QUEUE',
    label: 'QUEUE',
    icon: '📨',
    desc: 'Async writes',
    color: '#fb923c',
    defaultCapacity: 10000,
    defaultLatency: 5,
    costPerInstance: 40,
    defaultReplicas: 1,
    defaultErrorRate: 0.02,
  },
  {
    type: 'DB',
    label: 'DATABASE',
    icon: '🗄️',
    desc: 'Data store',
    color: '#fbbf24',
    defaultCapacity: 500,
    defaultLatency: 20,
    costPerInstance: 200,
    defaultReplicas: 1,
    defaultErrorRate: 0.1,
  },
]

export const nodeTypeMap = nodeTypes.reduce((a: Record<string, NodeType>, t: NodeType) => {
  a[t.type] = t
  return a
}, {})

export const templates: Template[] = [
  {
    name: 'MONOLITH',
    icon: '🧱',
    nodes: [
      { type: 'CLIENT', x: 50, y: 200, config: { inputTraffic: 2000, readPercent: 80 } },
      { type: 'LB', x: 300, y: 200 },
      { type: 'SERVICE', x: 550, y: 120, config: { replicas: 3 } },
      { type: 'SERVICE', x: 550, y: 280, config: { replicas: 3 } },
      { type: 'DB', x: 800, y: 200 },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 1, to: 3 },
      { from: 2, to: 4 },
      { from: 3, to: 4 },
    ],
  },
  {
    name: 'MICROSERVICES',
    icon: '🔬',
    nodes: [
      { type: 'CLIENT', x: 30, y: 220, config: { inputTraffic: 5000, readPercent: 70 } },
      { type: 'CDN', x: 200, y: 220 },
      { type: 'RATELIMIT', x: 370, y: 220 },
      { type: 'GATEWAY', x: 540, y: 220 },
      { type: 'SERVICE', x: 750, y: 80, config: { replicas: 2, instanceTier: 'large' } },
      { type: 'SERVICE', x: 750, y: 220, config: { replicas: 3, instanceTier: 'medium' } },
      { type: 'SERVICE', x: 750, y: 360, config: { replicas: 2, instanceTier: 'small' } },
      { type: 'CACHE', x: 980, y: 80, config: { instanceTier: 'small' } },
      { type: 'DB', x: 980, y: 220, config: { replicas: 2, instanceTier: 'large' } },
      { type: 'QUEUE', x: 980, y: 360, config: { instanceTier: 'medium' } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 3, to: 5 },
      { from: 3, to: 6 },
      { from: 4, to: 7 },
      { from: 5, to: 8 },
      { from: 6, to: 9 },
      { from: 7, to: 8 },
    ],
  },
  {
    name: 'EVENT DRIVEN',
    icon: '⚡',
    nodes: [
      { type: 'CLIENT', x: 50, y: 200, config: { inputTraffic: 3000, readPercent: 40 } },
      { type: 'GATEWAY', x: 280, y: 200 },
      { type: 'SERVICE', x: 500, y: 100, config: { replicas: 2, instanceTier: 'large' } },
      { type: 'QUEUE', x: 500, y: 300, config: { instanceTier: 'small' } },
      { type: 'SERVICE', x: 720, y: 300, config: { replicas: 4, instanceTier: 'medium' } },
      { type: 'CACHE', x: 720, y: 100 },
      { type: 'DB', x: 920, y: 200, config: { instanceTier: 'xlarge' } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 1, to: 3 },
      { from: 3, to: 4 },
      { from: 2, to: 5 },
      { from: 4, to: 6 },
      { from: 5, to: 6 },
    ],
  },
]

export const stressEvents: StressEvent[] = [
  {
    id: 'ddos',
    name: 'DDoS Attack',
    icon: '🔴',
    desc: 'Traffic x10, 100% read',
    color: '#ef4444',
    trafficMultiplier: 10,
    readPercentOverride: 100,
    duration: 15,
  },
  {
    id: 'flash-sale',
    name: 'Flash Sale',
    icon: '🛒',
    desc: 'Traffic x5, 80% write',
    color: '#f97316',
    trafficMultiplier: 5,
    readPercentOverride: 20,
    duration: 12,
  },
  {
    id: 'black-friday',
    name: 'Black Friday',
    icon: '🖤',
    desc: 'Traffic x3→x8 ramp',
    color: '#8b5cf6',
    trafficMultiplier: 8,
    duration: 20,
    rampUp: true,
  },
  {
    id: 'region-failover',
    name: 'Region Failover',
    icon: '💥',
    desc: '50% replicas down',
    color: '#dc2626',
    trafficMultiplier: 1,
    duration: 10,
  },
  {
    id: 'cascade-failure',
    name: 'Cascade Failure',
    icon: '⛓️',
    desc: '1 service fails 100%',
    color: '#b91c1c',
    trafficMultiplier: 1,
    duration: 10,
  },
]
