export const GAME_WIDTH = 1024
export const GAME_HEIGHT = 600
export const SHIP_SPEED = 7
export const FIRE_RATE = 150

export const WEAPON_TYPES = [
  {
    id: 0,
    name: 'Ion Laser',
    icon: '☀️',
    color: 'bg-yellow-400',
    speed: 25,
    size: 6,
    type: 'yellow',
    shape: 'beam',
  },
  {
    id: 1,
    name: 'Laser',
    icon: '⚡',
    color: 'bg-cyan-400',
    speed: 20,
    size: 4,
    type: 'blue',
    shape: 'dash',
  },
  {
    id: 2,
    name: 'Plasma',
    icon: '🔥',
    color: 'bg-red-500',
    speed: 12,
    size: 10,
    type: 'red',
    shape: 'plasma-fan',
  },
  {
    id: 3,
    name: 'Energy Wave',
    icon: '✨',
    color: 'bg-green-400',
    speed: 20,
    size: 12,
    type: 'green',
    shape: 'wave',
  },
  {
    id: 4,
    name: 'Neutron',
    icon: '🟣',
    color: 'bg-purple-500',
    speed: 25,
    size: 6,
    type: 'purple',
    shape: 'needle',
  },
  {
    id: 5,
    name: 'Lightning',
    icon: '🌩️',
    color: 'bg-blue-200',
    speed: 22,
    size: 24,
    type: 'lightning',
    shape: 'bolt',
  },
  {
    id: 6,
    name: 'Wavy Beam',
    icon: '🌀',
    color: 'bg-pink-500',
    speed: 40,
    size: 40,
    type: 'pink',
    shape: 'wavy-beam',
  },
  {
    id: 7,
    name: 'Acid Glob',
    icon: '🧪',
    color: 'bg-lime-500',
    speed: 10,
    size: 14,
    type: 'lime',
    shape: 'blob',
  },
  {
    id: 8,
    name: 'Magma Shard',
    icon: '🌋',
    color: 'bg-orange-600',
    speed: 18,
    size: 12,
    type: 'orange',
    shape: 'shard',
  },
]
